"""Tests for movie_video_continuity.extract_last_frame — real ffmpeg
subprocess calls (no mocking of subprocess itself, mirroring how
senses/eyes.py's capture_frame is the house style this borrows), run
against both a synthetic tiny clip and, when present, tonight's real
LTX-Video capability-test output."""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from sovereign_agent.movie_video_continuity import extract_last_frame

_REAL_CLIP = Path(
    "/home/kmon/.local/share/sovereign-agent/sandbox/movies/"
    "capability-test-clip-project/clips/"
    "1785228472_a_small_red_cube_on_a_plain_white_backgr.mp4"
)

pytestmark = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not installed")


def _make_synthetic_clip(path: Path) -> None:
    """A tiny real mp4 via ffmpeg's lavfi test source — genuinely
    generated by ffmpeg, not a hand-crafted fixture."""
    subprocess.run(
        ["ffmpeg", "-y", "-f", "lavfi", "-i", "testsrc=duration=1:size=64x64:rate=8",
         "-frames:v", "8", str(path)],
        capture_output=True, timeout=30, check=True,
    )


def test_extract_last_frame_missing_video_fails_cleanly(tmp_path):
    result = extract_last_frame(tmp_path / "nope.mp4")
    assert result.ok is False
    assert "not found" in result.detail


def test_extract_last_frame_from_synthetic_clip(tmp_path):
    clip = tmp_path / "synthetic.mp4"
    _make_synthetic_clip(clip)
    result = extract_last_frame(clip, output_path=tmp_path / "last.png")
    assert result.ok, result.detail
    assert Path(result.path).is_file()


def test_extract_last_frame_default_output_path(tmp_path):
    clip = tmp_path / "synthetic2.mp4"
    _make_synthetic_clip(clip)
    result = extract_last_frame(clip)
    assert result.ok, result.detail
    assert Path(result.path).name == "synthetic2_last_frame.png"
    Path(result.path).unlink(missing_ok=True)   # written next to the source clip — clean up


@pytest.mark.skipif(not _REAL_CLIP.is_file(), reason="tonight's real capability-test clip not present")
def test_extract_last_frame_from_real_generated_clip(tmp_path):
    result = extract_last_frame(_REAL_CLIP, output_path=tmp_path / "real_last_frame.png")
    assert result.ok, result.detail
    assert Path(result.path).stat().st_size > 0
