"""movie_assets — storage-aware tracking for movie project media.

movie-studio-d (Kevin, 2026-07-28): unlike game_assets.py (which gates
THIRD-PARTY downloads by license/domain), nothing here is downloaded from
anyone — every asset is either written by Aria (script/treatment) or
generated locally (storyboard stills now, video clips in Phase 2). So the
license/domain-allowlist half of game_assets.py doesn't apply; only the
storage-awareness half does, and it matters MORE here than it did for
games — generated video is large.

`check_workspace_budget()` is a soft per-project disk ceiling, same
philosophy this repo already applies to VRAM (see CLAUDE.md's vram.py
note) and to game workspaces, applied to a movie's generated media.
`record_asset()` appends every real generated asset (script, storyboard,
clip) to a plain, human-readable manifest — so Kevin (and Claude) can
always see what was produced and by which tool, without opening every file.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "ASSET_KINDS",
    "DEFAULT_MOVIE_WORKSPACE_BUDGET_BYTES",
    "BudgetStatus",
    "check_workspace_budget",
    "record_asset",
    "asset_manifest_path",
]

# What an asset can be — checked, not free-text, so the manifest stays
# meaningful. "clip" is here now so Phase 2 (real video generation) has
# nothing to add to this set later. "episode_cut" (movie-focus-d, Phase 3C)
# is the ffmpeg-assembled merge of a completed episode's clips.
ASSET_KINDS: frozenset[str] = frozenset({"script", "storyboard", "clip", "episode_cut"})

# Generous for stills + drafts; video will make this the real constraint
# once Phase 2 ships — the budget check is already in place for it.
DEFAULT_MOVIE_WORKSPACE_BUDGET_BYTES = 1024 * 1024 * 1024  # 1GB


@dataclass
class BudgetStatus:
    used_bytes: int
    budget_bytes: int

    @property
    def over_budget(self) -> bool:
        return self.used_bytes > self.budget_bytes

    @property
    def remaining_bytes(self) -> int:
        return max(0, self.budget_bytes - self.used_bytes)

    @property
    def used_mb(self) -> float:
        return round(self.used_bytes / (1024 * 1024), 1)

    @property
    def budget_mb(self) -> float:
        return round(self.budget_bytes / (1024 * 1024), 1)


def _dir_size_bytes(path: Path) -> int:
    total = 0
    if not path.is_dir():
        return 0
    for f in path.rglob("*"):
        if f.is_file():
            try:
                total += f.stat().st_size
            except OSError:
                continue
    return total


def check_workspace_budget(
    workspace_dir: Path,
    budget_bytes: int = DEFAULT_MOVIE_WORKSPACE_BUDGET_BYTES,
) -> BudgetStatus:
    """Real, measured disk usage under a movie project's workspace vs. its
    soft budget. Callers refuse new generation when over_budget is True
    rather than silently letting a project balloon."""
    return BudgetStatus(
        used_bytes=_dir_size_bytes(Path(workspace_dir)),
        budget_bytes=budget_bytes,
    )


def asset_manifest_path(workspace_dir: Path) -> Path:
    return Path(workspace_dir) / "ASSET_MANIFEST.md"


def record_asset(
    workspace_dir: Path,
    *,
    relative_path: str,
    kind: str,
    source_tool: str,
) -> Path:
    """Append one line to the project's plain, human-readable asset
    manifest. Called AFTER a successful generation — the caller (the
    generation tool) is responsible for the write having already
    succeeded before this is ever reached."""
    if kind not in ASSET_KINDS:
        raise ValueError(f"unknown asset kind {kind!r}; must be one of {sorted(ASSET_KINDS)}")
    path = asset_manifest_path(workspace_dir)
    is_new = not path.is_file()
    with open(path, "a", encoding="utf-8") as fh:
        if is_new:
            fh.write(
                "# Asset manifest\n\n"
                "Every generated asset in this project is recorded here — "
                "what it is, and which tool made it.\n\n"
            )
        fh.write(f"- `{relative_path}` — {kind} — generated by: {source_tool}\n")
    return path
