"""self_test — Aria writes tests for her own changes.

Every time Aria:
  - adds a new tool
  - modifies existing behavior
  - changes the UI
  - updates the agent loop

...she also writes a test for it, then runs it. No human
intervention needed — except when a test fails, then she
reports it and fixes it.

This module provides:
  - generate_tool_test(tool_class) -> str
  - generate_feature_test(feature_name, description) -> str
  - run_tests(pattern=None) -> TestResult
  - should_test(change_type, details) -> bool

Tests are written to <data>/tests/test_self_<feature>.py
and run with pytest. Results are stored in <data>/test_results.jsonl.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import SETTINGS


@dataclass
class TestResult:
    """Result of a test run."""
    test_id: str
    feature: str
    passed: bool
    total: int
    failures: int
    errors: int
    output: str
    timestamp: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class TestCase:
    """A single test case."""
    name: str
    description: str
    code: str
    tags: list[str] = field(default_factory=list)


class SelfTestWriter:
    """Generates and writes tests for Aria's own changes."""

    def __init__(self, data_dir: Path | None = None):
        self._data_dir = data_dir or SETTINGS.paths.data_dir
        self._tests_dir = self._data_dir / "tests"
        self._tests_dir.mkdir(parents=True, exist_ok=True)

    def generate_tool_test(self, tool_name: str, tool_class: str) -> str:
        """Generate a test file for a tool.

        Args:
            tool_name: The tool's name (e.g., "glob", "grep")
            tool_class: The tool's class name (e.g., "GlobTool", "GrepTool")

        Returns:
            The generated test file content
        """
        return f'''"""Self-test for {tool_name} tool.

Auto-generated by self_test.py when the {tool_name} tool was added/modified.
Tests the core functionality of the {tool_class} tool.
"""
from __future__ import annotations

import pytest
from sovereign_agent.tools import {tool_class}


@pytest.mark.asyncio
async def test_{tool_name}_tool_exists():
    """The {tool_name} tool can be instantiated."""
    tool = {tool_class}()
    assert tool is not None
    assert tool.name == "{tool_name}"


@pytest.mark.asyncio
async def test_{tool_name}_tool_has_required_attrs():
    """The {tool_name} tool has name, tier, description, failure_modes."""
    tool = {tool_class}()
    assert hasattr(tool, "name")
    assert hasattr(tool, "tier")
    assert hasattr(tool, "description")
    assert hasattr(tool, "failure_modes")
    assert isinstance(tool.failure_modes, tuple)
    assert len(tool.failure_modes) > 0


@pytest.mark.asyncio
async def test_{tool_name}_tool_schema():
    """The {tool_name} tool has a valid JSON schema."""
    schema = {tool_class}.schema()
    assert "type" in schema
    assert schema["type"] == "function"
    assert "function" in schema
    assert "parameters" in schema["function"]


@pytest.mark.asyncio
async def test_{tool_name}_tool_failure_modes_are_documented():
    """Every failure mode is mentioned in the description."""
    tool = {tool_class}()
    for mode in tool.failure_modes:
        assert mode.lower() in tool.description.lower(), (
            f"failure mode {{mode}} not mentioned in description"
        )


__all__ = [
    "test_{tool_name}_tool_exists",
    "test_{tool_name}_tool_has_required_attrs",
    "test_{tool_name}_tool_schema",
    "test_{tool_name}_tool_failure_modes_are_documented",
]
'''

    def generate_feature_test(
        self,
        feature_name: str,
        description: str,
        test_cases: list[TestCase],
    ) -> str:
        """Generate a test file for a feature.

        Args:
            feature_name: Short feature identifier (e.g., "approval_patterns")
            description: Human-readable description
            test_cases: List of test cases to include

        Returns:
            The generated test file content
        """
        lines = [
            f'"""Self-test for {feature_name}.',
            f"",
            f"Auto-generated by self_test.py.",
            f"",
            f"Description: {description}",
            f'"""',
            f"from __future__ import annotations",
            f"",
            f"import pytest",
            f"",
            f"",
        ]

        for tc in test_cases:
            lines.append(f"@pytest.mark.asyncio")
            lines.append(f"async def test_{tc.name}():")
            lines.append(f'    """{tc.description}"""')
            if tc.tags:
                lines.append(f"    # tags: {', '.join(tc.tags)}")
            lines.append(f"    {tc.code}")
            lines.append(f"")
            lines.append(f"")

        lines.append("")
        lines.append("__all__ = [")
        for tc in test_cases:
            lines.append(f'    "test_{tc.name}",')
        lines.append("]")

        return "\n".join(lines)

    def write_test(self, content: str, filename: str) -> Path:
        """Write a test file to the tests directory.

        Args:
            content: The test file content
            filename: The filename (e.g., "test_glob_tool.py")

        Returns:
            The path to the written file
        """
        test_path = self._tests_dir / filename
        test_path.write_text(content, encoding="utf-8")
        return test_path

    def run_tests(self, pattern: str | None = None) -> TestResult | None:
        """Run pytest on the self-tests directory.

        Args:
            pattern: Optional pytest pattern (e.g., "test_glob*")

        Returns:
            TestResult with the outcome, or None if pytest failed
        """
        args = [
            sys.executable, "-m", "pytest",
            str(self._tests_dir),
            "-q",
            "--tb=short",
            "--disable-warnings",
        ]
        if pattern:
            args.extend(["-k", pattern])

        try:
            result = subprocess.run(
                args,
                capture_output=True,
                text=True,
                timeout=300,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError) as e:
            return TestResult(
                test_id="error",
                feature="runner",
                passed=False,
                total=0,
                failures=0,
                errors=1,
                output=str(e),
                timestamp=datetime.now(timezone.utc).isoformat(),
            )

        output = result.stdout + result.stderr
        passed = result.returncode == 0

        # Parse pytest output for counts
        total = 0
        failures = 0
        errors = 0
        for line in output.splitlines():
            if "passed" in line and "failed" not in line:
                try:
                    total = int(line.split()[0])
                except (ValueError, IndexError):
                    pass
            if "failed" in line:
                try:
                    failures = int(line.split()[0])
                except (ValueError, IndexError):
                    pass

        test_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        return TestResult(
            test_id=test_id,
            feature=pattern or "all",
            passed=passed,
            total=total,
            failures=failures,
            errors=errors,
            output=output,
            timestamp=datetime.now(timezone.utc).isoformat(),
        )

    def record_result(self, result: TestResult) -> None:
        """Append a test result to the results log."""
        results_path = self._data_dir / "test_results.jsonl"
        results_path.parent.mkdir(parents=True, exist_ok=True)
        with results_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(result.to_dict(), ensure_ascii=False) + "\n")


def should_test(change_type: str, details: dict[str, Any]) -> bool:
    """Decide whether a change needs tests.

    Args:
        change_type: One of "tool_added", "tool_modified", "feature_added",
                     "ui_changed", "behavior_changed", "bug_fix"
        details: Context about the change

    Returns:
        True if tests should be generated/run
    """
    # Always test new tools
    if change_type == "tool_added":
        return True

    # Test modified tools
    if change_type == "tool_modified":
        return True

    # Test new features
    if change_type == "feature_added":
        return True

    # Test UI changes that affect behavior
    if change_type == "ui_changed" and details.get("affects_behavior", False):
        return True

    # Test behavior changes
    if change_type == "behavior_changed":
        return True

    # Don't test trivial bug fixes unless they affect public API
    if change_type == "bug_fix" and details.get("public_api", False):
        return True

    return False


__all__ = [
    "SelfTestWriter",
    "TestResult",
    "TestCase",
    "should_test",
]