#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
#  apply___PKG__.sh — TEMPLATE, generated by aria-new-module's new_module.sh.
#
#  Fill in the TODOs below once the payload tool(s) actually exist:
#    1. TOOL_FILES   — payload .py filenames to install under tools/
#    2. IMPORT_LINES — matching "from .X import Y" lines for tools/__init__.py
#    3. ALL_NAMES    — matching class names for tools/__init__.py's __all__
#
#  Pattern follows aria-screenshot/apply_screenshot.sh and
#  aria-game-dev-helpers/apply_game_dev_helpers.sh — both real, applied
#  modules; read either as a worked example if anything here is unclear.
#
#  Idempotent. Backs up __init__.py before patching.
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# root-detect-safety-d (found live 2026-08-03): an explicit $1 that
# didn't have the marker file used to fall through to the upward-search
# below, which silently resolves to $PWD's real repo instead — a
# disposable-worktree verify run ended up writing this module's tool
# into the LIVE repo instead of the worktree, undetected until manually
# checked. An explicit root is now trusted-or-refused, never silently
# overridden.
if [[ -n "${1:-}" ]]; then
  ROOT="$1"
  [[ -f "$ROOT/src/sovereign_agent/cli.py" ]] || {
    echo "✗ given root $ROOT has no src/sovereign_agent/cli.py — refusing to guess elsewhere"
    exit 1
  }
else
  ROOT="$PWD"
  if [[ ! -f "$ROOT/src/sovereign_agent/cli.py" ]]; then
    d="$PWD"
    while [[ "$d" != "/" ]]; do
      [[ -f "$d/src/sovereign_agent/cli.py" ]] && { ROOT="$d"; break; }
      d="$(dirname "$d")"
    done
  fi
  [[ -f "$ROOT/src/sovereign_agent/cli.py" ]] || { echo "✗ run from repo root"; exit 1; }
fi
echo "◊ repo root: $ROOT"

PKG="$ROOT/src/sovereign_agent"
TOOLS="$PKG/tools"
INIT="$TOOLS/__init__.py"
ts(){ date +%Y%m%d%H%M%S; }

# TODO: list every payload tool file to install, one per line.
TOOL_FILES=(
  # "__pkg___tool.py"
)

for f in "${TOOL_FILES[@]}"; do
  echo "→ installing tools/$f"
  cp "$HERE/payload/src/sovereign_agent/tools/$f" "$TOOLS/$f"
  echo "  ✓ tools/$f"
done

if [[ "${#TOOL_FILES[@]}" -gt 0 ]]; then
  echo "→ patching tools/__init__.py"
  cp "$INIT" "$INIT.bak.$(ts)"

  python3 - "$INIT" <<'PYEOF'
import sys, pathlib

init = pathlib.Path(sys.argv[1])
src = init.read_text(encoding="utf-8")
anchor = "from .write_file import WriteFileTool"
if anchor not in src:
    print("✗ write_file anchor not found in __init__.py", file=sys.stderr)
    sys.exit(1)

# TODO: fill in (import_line, class_name) pairs, e.g.:
#   ("from .__pkg___tool import __PkgTool", "__PkgTool"),
IMPORTS = [
    # ("from .MODULE import ClassName", "ClassName"),
]

prefix = ""
for line, _name in IMPORTS:
    marker = line.split(" import ")[0] + " import"
    if marker in src:
        print(f"  ↷ {line} already present — skipping import")
    else:
        prefix += line + "\n"
if prefix:
    src = src.replace(anchor, prefix + anchor, 1)
    print("  ✓ imports added")

old_all = '    "WriteFileTool",'
new_all_lines = "".join(
    f'    "{name}",\n' for _line, name in IMPORTS if f'"{name}"' not in src
)
if new_all_lines:
    if old_all not in src:
        print("✗ could not locate __all__ anchor — add tools manually", file=sys.stderr)
        sys.exit(1)
    src = src.replace(old_all, new_all_lines + old_all, 1)
    print("  ✓ __all__ entries added")
else:
    print("  ↷ __all__ entries already present or none declared — skipping")

init.write_text(src, encoding="utf-8")
print("  ✓ tools/__init__.py written")
PYEOF

  echo "→ compile check"
  python3 -m py_compile "${TOOL_FILES[@]/#/$TOOLS/}" "$INIT"
  echo "  ✓ compiles"
fi

echo "→ installing tests"
for t in "$HERE"/tests/test_*.py; do
  [[ -f "$t" ]] || continue
  cp "$t" "$ROOT/tests/$(basename "$t")"
  echo "  ✓ tests/$(basename "$t")"
done
for t in "$HERE"/tests/test_*.py; do
  [[ -f "$t" ]] || continue
  python3 -m py_compile "$ROOT/tests/$(basename "$t")"
done
echo "  ✓ tests compile"

echo
echo "✓ done. verify:"
echo "    .venv/bin/python -m pytest tests/test___PKG__*.py -v"
